### ISSUE TITLE
IANA TLD validation

### ISSUE THREAD

**Issue by BartBM** [spothero/SpotHeroEmailValidator-iOS#16]
The IANA list is not evaluated when the method validateSyntaxOfEmailAddress is called.
Is it possible to write an additional method or change the one above to incorporate TLD validation against the IANA list?

**Comment by designatednerd** [comment]
Yes, that's certainly possible. Updates to this aren't on our near-term priority list, unfortunately, so please feel free to open a pull request with this functionality if you'd like to see it added.
