### ISSUE TITLE
Semantic Versioning breaking change

### ISSUE THREAD

**Issue by longbct** [spothero/SpotHeroEmailValidator-iOS#34]
After version 2.0.1 published, all of our auto-build system is failed due to there is some breaking changes in the 2.0.1 and require us to update the codebase to match the new changes. But we would like to suggest this great lib to get some Semantic Versioning protocol such as, 

Given a version number MAJOR.MINOR.PATCH, increment the
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.

so if there is a breaking change introduced, we should better increment the MAJOR version so it will keep all the existing user's project to not bring that breaking version into their system since lots of people is using "pod ~> x.y.z" in the pod file.

**Comment by bdrelling** [comment]
@longbct thanks for reporting this and sorry for the delay. Our repo does follow Semantic Versioning, but it seems like some changes were pulled into the 2.0.1 update unintentionally. I pushed 2.0.2 to revert those changes, which should now be in the 3.0.0-beta.1 build specifically.

Given our plans for this repository, you're also safe pinning to the exact version 2.0.0 as our next release of the library will likely be in the 3.x line which will introduce breaking changes.

Let me know if the 2.0.2 push fixes things for you!

**Comment by bdrelling** [comment]
Closing this as I haven't heard anything back. @longbct please reach out if you have any other issues.
